default: &default
  gateway:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: gateway
    pool: 5
    username: gateway
    password: pass4u
    host: 10.140.0.11
    port: 3306
  restaurant:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: restaurant
    pool: 5
    username: gateway
    password: pass4u
    host: 10.140.0.11
    port: 3306
  sevenroom:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: sevenroom
    pool: 25
    username: gateway
    password: pass4u
    host: 10.140.0.11
    port: 3306
#
# production specific
#
production:
  gateway:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: bindo_gateway
    pool: 5
    username: sevenroom
    password: BindoPass4u
    host: db-master.prd.tw.bindo.in
    port: 3306
  restaurant:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: restaurant
    pool: 5
    username: sevenroom
    password: BindoPass4u
    host: db-master.prd.tw.bindo.in
    port: 3306
  sevenroom:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    database: sevenroom
    pool: 25
    username: sevenroom
    password: BindoPass4u
    host: db-master.prd.tw.bindo.in
    port: 3306
#
# development specific
#
staging:
  <<: *default
