default: &default
  op_url: "https://demo.sevenrooms.com/api-ext/2_2/"
  client_id: "17dfb0fbf5aa0e1063557b43710f9e6583e00f30e819416145103d2bb86e764edea8527af0dd3b8e9cc5fe03bb4877579a661363b85407e2da6caa39b621e9bc"
  client_secret: "eb66a261d6b388b52bf63c61e2fd96fd957f4e5aec111d4324a9bb8974d46989f659905fd3c23d2f5a771b395026d8c285bc366ac7af4edb3a4b0b3607a187cc"
  pos_id: "bindo"
  retry: 3
  stores:
    "1":
      name: "test1"
      store_id: 7264
      venue_id: ahhzfnNldmVucm9vbXMtc2VjdXJlLWRlbW9yHAsSD25pZ2h0bG9vcF9WZW51ZRiAgJDK1LuZCQw
    # "2":
    #   name: "test2"
    #   store_id: 5807
    #   op_api_key: 691abcdb44eefbaf376709872ad798f6
#
# production specific
#
production:
  <<: *default
  op_url: "https://app.sevenrooms.com/en/admin/restaurant/check/interface"
  op_api_key: 691abcdb44eefbaf376709872ad798f6
  retry: 3
  stores:
    "Royal Plaza Hotel - Di King Heen":
      name: "Royal Plaza Hotel - Di King Heen"
      store_id: 33860
      op_api_key: 0289f3e8699442878b803e24b415b478
    "Royal Plaza Hotel - La Scala":
      name: "Royal Plaza Hotel - La Scala"
      store_id: 33852
      op_api_key: f08e00b912354f85bd04fe39ad02c8c4
    "Royal Plaza Hotel - Lion Rock":
      name: "Royal Plaza Hotel - Di King Heen"
      store_id: 33864
      op_api_key: 13655d4ca720482c94e86a53dbc9be59

#
# development specific
#
staging:
  <<: *default
